services:
  postgres:
    image: postgres:16
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: user-service-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/user_service
      DB_USER: postgres
      DB_PASSWORD: postgres
    stdin_open: true
    tty: true

  tests:
    image: maven:3.9.8-eclipse-temurin-21
    working_dir: /app
    command: mvn test
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      DOCKER_API_VERSION: "1.54"
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
    volumes:
      - .:/app
      - ${HOME}/.docker/run/docker.sock:/var/run/docker.sock
      - maven_repo:/root/.m2

volumes:
  postgres_data:
  maven_repo:
